image: registry.secoder.net/tool/deployer

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - export BUILD_IMAGE_NAME=$CI_REGISTRY_IMAGE
    - export BUILD_IMAGE_TAG=$CI_COMMIT_REF_SLUG
    - export BUILD_IMAGE_USERNAME=$CI_REGISTRY_USER
    - export BUILD_IMAGE_PASSWORD=$CI_REGISTRY_PASSWORD
    - deployer build

# Job template for test stage
.test:
  image: python:3.8.5
  stage: test


  before_script:
    - pip install -i https://pypi.tuna.tsinghua.edu.cn/simple django==3.1.1
    - pip install -i https://pypi.tuna.tsinghua.edu.cn/simple Pillow==7.2.0
    - pip install -i https://pypi.tuna.tsinghua.edu.cn/simple requests==2.24.0
    - pip install -i https://pypi.tuna.tsinghua.edu.cn/simple django-cors-headers==3.5.0
    - python manage.py makemigrations board
    - python manage.py makemigrations log
    - python manage.py makemigrations task
    - python manage.py makemigrations answer
    - python manage.py migrate

unit-test:
  extends: .test
  script:
    python manage.py test

deploy:
  stage: deploy
  script:
    - deployer dyno replace $CI_PROJECT_NAME "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" "$REGISTRY_USER" "$REGISTRY_PWD"
  only:
    - master